/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export { AchievementDto } from './models/AchievementDto';
export type { AchievementGrantRequestDto } from './models/AchievementGrantRequestDto';
export type { ActivitiesFeedPaginatedResponseDto } from './models/ActivitiesFeedPaginatedResponseDto';
export type { ActivitiesPaginatedResponseDto } from './models/ActivitiesPaginatedResponseDto';
export { Activity } from './models/Activity';
export type { ActivityComment } from './models/ActivityComment';
export type { ActivityCommentDto } from './models/ActivityCommentDto';
export type { BlogPost } from './models/BlogPost';
export type { BlogPostImage } from './models/BlogPostImage';
export type { BlogPostReview } from './models/BlogPostReview';
export type { BlogPostTag } from './models/BlogPostTag';
export { Collection } from './models/Collection';
export type { CollectionEntriesPaginatedResponseDto } from './models/CollectionEntriesPaginatedResponseDto';
export { CollectionEntry } from './models/CollectionEntry';
export type { CollectionEntryFavoriteStatusDto } from './models/CollectionEntryFavoriteStatusDto';
export type { CollectionEntryToCollection } from './models/CollectionEntryToCollection';
export { ConnectionCreateDto } from './models/ConnectionCreateDto';
export type { CreateAchievementCodeRequestDto } from './models/CreateAchievementCodeRequestDto';
export type { CreateAchievementCodeResponseDto } from './models/CreateAchievementCodeResponseDto';
export type { CreateCollectionDto } from './models/CreateCollectionDto';
export { CreateCommentDto } from './models/CreateCommentDto';
export type { CreatePostDto } from './models/CreatePostDto';
export { CreateReportRequestDto } from './models/CreateReportRequestDto';
export type { CreateReviewDto } from './models/CreateReviewDto';
export type { CreateUpdateBlogPostDto } from './models/CreateUpdateBlogPostDto';
export type { CreateUpdateBlogPostReviewInfoDto } from './models/CreateUpdateBlogPostReviewInfoDto';
export { CreateUpdateCollectionEntryDto } from './models/CreateUpdateCollectionEntryDto';
export type { CursorPaginationInfo } from './models/CursorPaginationInfo';
export { DeleteCommentDto } from './models/DeleteCommentDto';
export type { FindAllBlogPostResponseDto } from './models/FindAllBlogPostResponseDto';
export { FindAllCommentsDto } from './models/FindAllCommentsDto';
export { FindAllPlaytimeFiltersDto } from './models/FindAllPlaytimeFiltersDto';
export type { FindAllPlaytimeResponseDto } from './models/FindAllPlaytimeResponseDto';
export type { FindAllProfileResponseItemDto } from './models/FindAllProfileResponseItemDto';
export type { FindAllReviewsByIdDto } from './models/FindAllReviewsByIdDto';
export { FindAvailableConnectionsResponseDto } from './models/FindAvailableConnectionsResponseDto';
export { FindCollectionEntriesForCollectionIdDto } from './models/FindCollectionEntriesForCollectionIdDto';
export type { FindCollectionEntriesGameFilterDto } from './models/FindCollectionEntriesGameFilterDto';
export type { FindCollectionEntriesOrderBy } from './models/FindCollectionEntriesOrderBy';
export type { FindCommentsPaginatedResponseDto } from './models/FindCommentsPaginatedResponseDto';
export type { FindExternalGamesResponseDto } from './models/FindExternalGamesResponseDto';
export { FindOneStatisticsDto } from './models/FindOneStatisticsDto';
export type { FindRelatedCollectionEntriesResponseDto } from './models/FindRelatedCollectionEntriesResponseDto';
export type { FindReviewPaginatedDto } from './models/FindReviewPaginatedDto';
export { FindStatisticsTrendingGamesDto } from './models/FindStatisticsTrendingGamesDto';
export { FindStatisticsTrendingReviewsDto } from './models/FindStatisticsTrendingReviewsDto';
export { FollowInfoRequestDto } from './models/FollowInfoRequestDto';
export type { FollowInfoResponseDto } from './models/FollowInfoResponseDto';
export type { FollowRegisterDto } from './models/FollowRegisterDto';
export type { FollowRemoveDto } from './models/FollowRemoveDto';
export type { FollowStatusDto } from './models/FollowStatusDto';
export { Game } from './models/Game';
export { GameAchievementDto } from './models/GameAchievementDto';
export { GameAchievementGroupDto } from './models/GameAchievementGroupDto';
export { GameAchievementWithObtainedInfo } from './models/GameAchievementWithObtainedInfo';
export type { GameAlternativeName } from './models/GameAlternativeName';
export type { GameArtwork } from './models/GameArtwork';
export type { GameCollection } from './models/GameCollection';
export type { GameCompany } from './models/GameCompany';
export type { GameCompanyLogo } from './models/GameCompanyLogo';
export type { GameCover } from './models/GameCover';
export type { GameEngine } from './models/GameEngine';
export type { GameEngineLogo } from './models/GameEngineLogo';
export { GameExternalGame } from './models/GameExternalGame';
export { GameExternalStoreDto } from './models/GameExternalStoreDto';
export type { GameFranchise } from './models/GameFranchise';
export type { GameGenre } from './models/GameGenre';
export type { GameInvolvedCompany } from './models/GameInvolvedCompany';
export type { GameKeyword } from './models/GameKeyword';
export type { GameLocalization } from './models/GameLocalization';
export type { GameMode } from './models/GameMode';
export { GameObtainedAchievementDto } from './models/GameObtainedAchievementDto';
export { GamePlatform } from './models/GamePlatform';
export type { GamePlayerPerspective } from './models/GamePlayerPerspective';
export type { GameRepositoryFilterDto } from './models/GameRepositoryFilterDto';
export type { GameRepositoryFindAllDto } from './models/GameRepositoryFindAllDto';
export type { GameRepositoryFindOneDto } from './models/GameRepositoryFindOneDto';
export type { GameScreenshot } from './models/GameScreenshot';
export type { GameStatistics } from './models/GameStatistics';
export type { GameStatisticsPaginatedResponseDto } from './models/GameStatisticsPaginatedResponseDto';
export type { GameTheme } from './models/GameTheme';
export type { GameTimeToBeatDto } from './models/GameTimeToBeatDto';
export type { GetPostsPaginatedResponseDto } from './models/GetPostsPaginatedResponseDto';
export type { GetRecommendationsResponseDto } from './models/GetRecommendationsResponseDto';
export { HandleReportRequestDto } from './models/HandleReportRequestDto';
export type { ImporterPaginatedResponseDto } from './models/ImporterPaginatedResponseDto';
export { ImporterResponseItemDto } from './models/ImporterResponseItemDto';
export type { ImporterStatusUpdateRequestDto } from './models/ImporterStatusUpdateRequestDto';
export { ImporterWatchNotification } from './models/ImporterWatchNotification';
export type { JournalEntryDayGroupDto } from './models/JournalEntryDayGroupDto';
export type { JournalEntryMonthGroupDto } from './models/JournalEntryMonthGroupDto';
export { JournalEntryStatusDto } from './models/JournalEntryStatusDto';
export type { JournalEntryYearGroupDto } from './models/JournalEntryYearGroupDto';
export type { JournalOverviewResponseDto } from './models/JournalOverviewResponseDto';
export { JournalPlaylogEntryDto } from './models/JournalPlaylogEntryDto';
export { JournalPlaylogGroupDto } from './models/JournalPlaylogGroupDto';
export type { Library } from './models/Library';
export { Notification } from './models/Notification';
export { NotificationAggregateDto } from './models/NotificationAggregateDto';
export type { NotificationViewUpdateDto } from './models/NotificationViewUpdateDto';
export type { Object } from './models/Object';
export type { ObtainedAchievementDto } from './models/ObtainedAchievementDto';
export type { PaginatedAchievementsResponseDto } from './models/PaginatedAchievementsResponseDto';
export type { PaginatedNotificationAggregationDto } from './models/PaginatedNotificationAggregationDto';
export type { PaginatedReportResponseDto } from './models/PaginatedReportResponseDto';
export type { PaginationInfo } from './models/PaginationInfo';
export type { PlaytimeFilterOrderBy } from './models/PlaytimeFilterOrderBy';
export type { Post } from './models/Post';
export type { PostComment } from './models/PostComment';
export type { PostCommentDto } from './models/PostCommentDto';
export type { Profile } from './models/Profile';
export type { ProfileAvatar } from './models/ProfileAvatar';
export type { ProfileBanner } from './models/ProfileBanner';
export type { ProfileMetricsOverviewDto } from './models/ProfileMetricsOverviewDto';
export type { ProfileMetricsTypeDistributionItem } from './models/ProfileMetricsTypeDistributionItem';
export type { ProfileMetricsTypeDistributionResponseDto } from './models/ProfileMetricsTypeDistributionResponseDto';
export type { ProfileMetricsYearDistributionItem } from './models/ProfileMetricsYearDistributionItem';
export type { ProfileMetricsYearDistributionResponseDto } from './models/ProfileMetricsYearDistributionResponseDto';
export type { PsnAchievementDetails } from './models/PsnAchievementDetails';
export type { PsnExtraMappings } from './models/PsnExtraMappings';
export { Report } from './models/Report';
export type { Review } from './models/Review';
export type { ReviewComment } from './models/ReviewComment';
export type { ReviewCommentDto } from './models/ReviewCommentDto';
export type { ReviewScoreDistribution } from './models/ReviewScoreDistribution';
export type { ReviewScoreResponseDto } from './models/ReviewScoreResponseDto';
export type { ReviewStatistics } from './models/ReviewStatistics';
export type { ReviewStatisticsPaginatedResponseDto } from './models/ReviewStatisticsPaginatedResponseDto';
export { StatisticsActionDto } from './models/StatisticsActionDto';
export type { StatisticsStatus } from './models/StatisticsStatus';
export type { SteamAchievementDetails } from './models/SteamAchievementDetails';
export { SubmitExternalGameDto } from './models/SubmitExternalGameDto';
export { SubmitUserPlaytimeDto } from './models/SubmitUserPlaytimeDto';
export { UnmappedExternalGame } from './models/UnmappedExternalGame';
export type { UpdateBlogPostImageDto } from './models/UpdateBlogPostImageDto';
export type { UpdateCollectionDto } from './models/UpdateCollectionDto';
export { UpdateCommentDto } from './models/UpdateCommentDto';
export type { UpdateFeaturedObtainedAchievementDto } from './models/UpdateFeaturedObtainedAchievementDto';
export type { UpdateFeaturedObtainedAchievementV2Dto } from './models/UpdateFeaturedObtainedAchievementV2Dto';
export type { UpdateProfileDto } from './models/UpdateProfileDto';
export { UpdateProfileImageDto } from './models/UpdateProfileImageDto';
export type { UploadPostImageRequestDto } from './models/UploadPostImageRequestDto';
export type { UploadPostImageResponseDto } from './models/UploadPostImageResponseDto';
export { UserConnectionDto } from './models/UserConnectionDto';
export type { UserCumulativePlaytimeDto } from './models/UserCumulativePlaytimeDto';
export type { UserFollow } from './models/UserFollow';
export type { UserLevel } from './models/UserLevel';
export { UserPlaytime } from './models/UserPlaytime';
export { UserPlaytimeDto } from './models/UserPlaytimeDto';
export type { XboxAchievementDetails } from './models/XboxAchievementDetails';

export { AchievementsService } from './services/AchievementsService';
export { AchievementsCodeService } from './services/AchievementsCodeService';
export { ActivitiesService } from './services/ActivitiesService';
export { ActivitiesFeedService } from './services/ActivitiesFeedService';
export { AuthService } from './services/AuthService';
export { BlogPostService } from './services/BlogPostService';
export { CollectionsService } from './services/CollectionsService';
export { CollectionsEntriesService } from './services/CollectionsEntriesService';
export { CommentService } from './services/CommentService';
export { ConnectionsService } from './services/ConnectionsService';
export { ExternalGameService } from './services/ExternalGameService';
export { FollowService } from './services/FollowService';
export { GameAchievementService } from './services/GameAchievementService';
export { GameRepositoryService } from './services/GameRepositoryService';
export { HealthService } from './services/HealthService';
export { ImporterService } from './services/ImporterService';
export { ImporterWatchService } from './services/ImporterWatchService';
export { JournalService } from './services/JournalService';
export { LevelService } from './services/LevelService';
export { LibrariesService } from './services/LibrariesService';
export { NotificationsService } from './services/NotificationsService';
export { PlaytimeService } from './services/PlaytimeService';
export { PlaytimeTtbService } from './services/PlaytimeTtbService';
export { PostsService } from './services/PostsService';
export { PostsFeedService } from './services/PostsFeedService';
export { ProfileService } from './services/ProfileService';
export { ProfileMetricsService } from './services/ProfileMetricsService';
export { RecommendationService } from './services/RecommendationService';
export { ReportService } from './services/ReportService';
export { ReviewsService } from './services/ReviewsService';
export { StatisticsService } from './services/StatisticsService';
export { StatisticsQueueService } from './services/StatisticsQueueService';
export { SyncIgdbService } from './services/SyncIgdbService';
