name: Build Android Bundle

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install app dependencies
        run: yarn install

      - name: Capacitor update
        run: yarn build -F mobile

      - name: Build app bundle
        working-directory: apps/mobile
        run: cd android && ./gradlew bundle

      - name: Extract Android signing key from env
        working-directory: apps/mobile
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks

      - name: Sign dev build
        working-directory: apps/mobile
        run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASS }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release

      - name: Upload release bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: apps/mobile/android/app/build/outputs/bundle/release/app-release-signed.aab
          retention-days: 30

